import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const yamlPath = resolve(import.meta.dir, '..', '.context', 'SRS', 'api-contracts.yaml');
const yaml = readFileSync(yamlPath, 'utf-8');

const escaped = yaml
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$/g, '\\$');

const output = `// Auto-generated by embed-spec.ts — do not edit
const apiSpecYaml = \`${escaped}\`;
export default apiSpecYaml;
`;

const outPath = resolve(import.meta.dir, '..', 'server', 'src', 'api-spec-content.ts');
await Bun.write(outPath, output);
console.log(`Generated ${outPath} (${output.length} bytes)`);
